pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=Unit Tests - Node.js (10.x)
      - check-success=Unit Tests - Node.js (12.x)
      - check-success=Unit Tests - Node.js (14.x)
      - check-success=Unit Tests and Test Coverage - Node.js 16.x
      - check-success=codecov/project
      - check-success=codecov/patch
      - "check-success=LGTM analysis: JavaScript"
    actions:
      merge:
        method: rebase

  - name: Delete head branch after merge if PR was created by dependabot
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - merged
    actions:
      delete_head_branch:
